### ISSUE TITLE
Icon positions are not correct in production

### ISSUE THREAD

**Issue by rstammer** [tsechingho/ckeditor-rails#35]
All notes are due to a Rails 4 App.

Everything is fine in development mode, but in production the background-position of all item icons are seem to be "shifted" (see picture below).

![image](https://f.cloud.github.com/assets/3685123/1148226/5c49a270-1ebc-11e3-8cda-90cb242a4761.png)

Inspecting the buttons with firebug led me to the following css-class, e.g. for the "bold"-button:

``` css
.cke_button__bold_icon {
background: url(icons.png) no-repeat 0 -32px !important;
}
```

This seems to collide with some other class, since disabling the class .cke_button__bold_icon solves the problem and lets the button look nice. 

Can anyone reproduce this?  

Best wishes,
Robin
